### ISSUE TITLE
关于行为树章节中的问题

### ISSUE THREAD

**Issue by ctzcs** [luzexi/Unity3dToBeLeader#10]
在7.2.1节中，关于并行节点这里，这里的selector和squence的条件和结果是不是说反了，不是和非并行的一样，selector相当于||，sequence相当于&&吗？
“·Parallel Selector Node，即并行选择节点。其规则为执行完所有子节点后，如果有一个子节点返回False，则自己向父节点返回False，只有当所有子节点全返回True时，自己才向父节点返回True。·Parallel Sequence Node，即并行顺序节点。其规则为执行完所有子节点后，如果有一个子节点返回True，则自己向父节点返回True，否则，只有当全部子节点返回False时，自己才向父节点返回False。”

**Comment by luzexi** [comment]
收到，不错哟^_^
Parallel Selector 和 Selector 不同，前者会把子节点都执行完，后者当遇到true子节点后立即停止迭代
