### ISSUE TITLE
【勘误】第13页第二行有表述错误

### ISSUE THREAD

**Issue by XINCGer** [luzexi/Unity3dToBeLeader#3]
RT
书上写的是：“数据表：EXL导为二进制文件....”
看了一下博客上的原文：“数据表 -- XLS导为二进制文件还是Json或其他格式，读取接口和解析接口的定义。”
EXL 应该为 XLS 或者Excel

**Comment by luzexi** [comment]
Good，优秀

> RT 书上写的是：“数据表：EXL导为二进制文件....” 看了一下博客上的原文：“数据表 -- XLS导为二进制文件还是Json或其他格式，读取接口和解析接口的定义。” EXL 应该为 XLS 或者Excel

**Comment by luzexi** [comment]
已修复进书中，会在第二次重印的批次中体现
