### ISSUE TITLE
文字错误  1.2章  软件架构思维方式

### ISSUE THREAD

**Issue by ovo123** [luzexi/Unity3dToBeLeader#5]
大佬，你好；
        我在阅读的时候发现一个字的错误
       “ 架构既承载了我们对这个项目的抽象思维，也帮助我们_厘_**(我想这里应该是梳理的‘理’)**清了业务体系的方向。如果要问软件研发、架构设计中最重要的能力是什么，我会毫不犹豫回答是抽象能力。”

**Comment by luzexi** [comment]
点赞
