### ISSUE TITLE
第四章：用户界面 104页

### ISSUE THREAD

**Issue by lswzzz** [luzexi/Unity3dToBeLeader#7]
原文：
继承型是指事件先响应到基类，再由基类反馈到父类，由父类做处理，这样UI既可以得到对输入事件的响应，也可以自行修改自己需要的逻辑

这里的父类应该是子类吧？后面那句“自行修改自己需要的逻辑”表意比较模糊，可以修改成“覆写基类的响应方法”

**Comment by luzexi** [comment]
666，你是语文专业出生的吧，文字能力很强。记下了
