### ISSUE TITLE
第八章 281页有错

### ISSUE THREAD

**Issue by lswzzz** [luzexi/Unity3dToBeLeader#8]
图8-37 外围多边形点顺序是顺时针的，内多边形点显示也是顺时针。这里内多边形点应该是逆时针才对。

另外图8-38的解释并不清晰，这里应该说明是从点6和7生成了两个新的点12,11
原始图包含一个外围多边形{1,2,3,4,5,6} 和一个内多边形{7,8,9,10}
通过算法将两个多边形合并后为{1,2,3,4,5,6,7,8,9,10,11,12}

**Comment by luzexi** [comment]
Good，具体细节我看下
