### ISSUE TITLE
第八章 302页

### ISSUE THREAD

**Issue by lswzzz** [luzexi/Unity3dToBeLeader#9]
302页有一段描述为：
Unity3D静态批处理的规则比较严格，即要求材质球相同，贴图的模型相同。

这里“贴图的模型相同”的描述是错的，应该是“模型的顶点属性相同”。如果一个模型有光照贴图UV，另一个没有，他们是不能合批的。

还有一个小错误，301页：
三角形数据再进入渲染管线后开启的是GPU并行处理，CPU原本的单行线处理变成了多线处理。

**Comment by luzexi** [comment]
Good。
引擎上的合批与剔除我另写了篇文章
这里有很多细节，你可以参考下

https://mp.weixin.qq.com/s?__biz=MzU1ODY1ODY2NA==&mid=2247485541&idx=1&sn=1adc3d4bd3573b58dbc56e81be963abf&chksm=fc226d62cb55e474965abb9a2fbbff8eee8daaa2e541310279178af01984c0882060273fe026&token=546801700&lang=zh_CN#rd
